= JEP-0000: Matrix syntax for Declarative Pipeline
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="1h,1"]
|===
| JEP
| 0000

| Title
| Matrix syntax for Declarative Pipeline

| Sponsor
| link:https://github.com/abayer[Andrew Bayer]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted :information_source:

| Type
| Informational, or Process

| Created
| 2018-08-24

| BDFL-Delegate
| TBD

| JIRA
| https://issues.jenkins-ci.org/browse/JENKINS-40986[JENKINS-40986]

//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
//| Requires
//| :bulb: JEP-NUMBER, JEP-NUMBER... :bulb:
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===

== Abstract

Declarative Pipeline has a `matrix` syntax, allowing for declaring a set of
sequential stages to run with each combination of a set of variables, each with
multiple possible values.

== Specification

[TIP]
====
Provide a detailed specification what is being proposed.
Be as technical and detailed as needed to allow new or existing Jenkins developers
to reasonably understand the scope/impact of an implementation.

* Use present tense - describe what the proposal "does" (as if it were already done) not what it will do.
* Do not discuss alternative designs that were rejected, those belong in the Reasoning section.
* Avoid in-depth discussion or justification of design choices, that belongs in the Reasoning section.
====

== Motivation

While the parallel and sequential stages features in Declarative Pipeline
provide Pipeline authors with the means to write complex Pipelines to be
executed across multiple environments, using those features alone still
requires a fair amount of repetition of Declarative directives, stages, steps,
etc in order to run the same chunk of Declarative code in multiple contexts.
There has been no equivalent to the Freestyle-related Matrix project type for
Pipeline without dynamic generation of stages via loops/scripting/etc and the
`parallel` step. That pattern does not fit into Declarative syntax, nor will it
be cleanly visualized in Blue Ocean.

This proposal addresses those gaps by providing a pure Declarative syntax,
with execution running on top of the existing parallel and sequential stages
functionality. This will let Pipeline authors avoid code duplication (with all
the potential for typos, missed changes, readability concerns, etc that code
duplication entails) and write more readable, consistent, and stable Pipelines
for executing across multiple platforms, environments, and so on. In addition,
the existing support for visualization of parallel and sequential stages in
Blue Ocean will apply to Pipelines using the `matrix` syntax as well.

== Reasoning

[TIP]
====
Explain why particular design decisions were made.
Describe alternate designs that were considered and related work, e.g. how the feature is supported in other systems.
Provide evidence of consensus within the community and discuss important objections or concerns raised during discussion.

* Use sub-headings to organize this section for ease of readability.
* Do not talk about history or why this needs to be done, that is part of Motivation section.
====

== Backwards Compatibility

There are no backwards compatibility concerns related to this proposal.

== Security

There are no security risks related to this proposal.

== Infrastructure Requirements

There are no new infrastructure requirements related to this proposal.

== Testing

[TIP]
====
If the JEP involves any kind of behavioral change to code
(whether in a Jenkins product or backend infrastructure),
give a summary of how its correctness (and, if applicable, compatibility, security, etc.) can be tested.

In the preferred case that automated tests can be developed to cover all significant changes, simply give a short summary of the nature of these tests.

If some or all of changes will require human interaction to verify, explain why automated tests are considered impractical.
Then summarize what kinds of test cases might be required: user scenarios with action steps and expected outcomes.
Might behavior vary by platform (operating system, servlet container, web browser, etc.)?
Are there foreseeable interactions between different permissible versions of components (Jenkins core, plugins, etc.)?
Are any special tools, proprietary software, or online service accounts required to exercise a related code path (Active Directory server, GitHub login, etc.)?
When will testing take place relative to merging code changes, and might retesting be required if other changes are made to this area in the future?

If this proposal requires no testing, this section may simply say:
There are no testing issues related to this proposal.
====

== Prototype Implementation

[TIP]
====
Link to any open source reference implementation of code changes for this proposal.
The implementation need not be completed before the JEP is
link:https://github.com/jenkinsci/jep/tree/master/jep/1#accepted[accepted],
but must be completed before any JEP is given
"link:https://github.com/jenkinsci/jep/tree/master/jep/1#final[Final]" status.

JEPs which will not include code changes may omit this section.
====

== References

[TIP]
====
Provide links to any related documents.
This will include links to discussions on the mailing list, pull requests, and meeting notes.
====



